// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxReceipt.API.Data;

#nullable disable

namespace TaxReceipt.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("TaxReceipt.API.Models.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RncCedula")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RncCedula");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("TaxReceipt.API.Models.Contribuyente", b =>
                {
                    b.Property<long>("RncCedula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RncCedula");

                    b.ToTable("Contribuyentes");
                });

            modelBuilder.Entity("TaxReceipt.API.Models.Comprobante", b =>
                {
                    b.HasOne("TaxReceipt.API.Models.Contribuyente", "Contribuyente")
                        .WithMany("Comprobantes")
                        .HasForeignKey("RncCedula")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contribuyente");
                });

            modelBuilder.Entity("TaxReceipt.API.Models.Contribuyente", b =>
                {
                    b.Navigation("Comprobantes");
                });
#pragma warning restore 612, 618
        }
    }
}
